name: CMake

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake LibrariesSandbox
      run: cd ${{github.workspace}}/LibrariesSandbox && cmake -B ${{github.workspace}}/LibrariesSandbox/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build LibrariesSandbox
      run: cmake --build ${{github.workspace}}/LibrariesSandbox/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/LibrariesSandbox/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
